name: "Deploy VPN"

on:
  workflow_dispatch:

env:
  AWS_REGION: eu-south-1

jobs:



  generate-private-key-locally:
    name: Generate private key
    timeout-minutes: 1500
    runs-on: ubuntu-latest
    container:
      image: ubuntu
      volumes:
        - ./:/vpn
    steps:
      - run: apt-get update
      - run: apt-get install curl -y
      - run: apt-get install gpg -y
      - run: mkdir -p /etc/apt/keyrings # directory does not exist on older releases
      - run: curl -fsSL https://swupdate.openvpn.net/repos/repo-public.gpg | gpg --dearmor > /etc/apt/keyrings/openvpn-repo-public.gpg
      - run: echo "deb [arch=arm64 signed-by=/etc/apt/keyrings/openvpn-repo-public.gpg] https://build.openvpn.net/debian/openvpn/stable jammy main" > /etc/apt/sources.list.d/openvpn-aptrepo.list
      - run: apt-get update
      - run: apt-get install openvpn -y
      - run: mkdir vpn
      - run: openvpn --genkey --secret static.key
      - run: echo "SECRET_KEY=$(cat static.ley)" >> $GITHUB_OUTPUT
      - uses: "DamianReeves/write-file-action@master"
        with:
          path: openvpn.conf
          write-mode: overwrite
          contents: |
            remote myremote.mydomain
            dev tun
            ifconfig 10.8.0.2 10.8.0.1
            secret static.key


  deploy-vpn-remote:
    name: Deploy VPN Remote
    timeout-minutes: 1500
    runs-on: vpn
    needs: generate-private-key-locally
    container:
      image: ubuntu
    steps:
      - run: apt-get update
      - run: apt-get install curl -y
      - run: apt-get install gpg -y
      - run: mkdir -p /etc/apt/keyrings # directory does not exist on older releases
      - run: curl -fsSL https://swupdate.openvpn.net/repos/repo-public.gpg | gpg --dearmor > /etc/apt/keyrings/openvpn-repo-public.gpg
      - run: echo "deb [arch=arm64 signed-by=/etc/apt/keyrings/openvpn-repo-public.gpg] https://build.openvpn.net/debian/openvpn/stable jammy main" > /etc/apt/sources.list.d/openvpn-aptrepo.list
      - run: apt-get update
      - run: apt-get install openvpn -y
      - uses: "DamianReeves/write-file-action@master"
        with:
          path: openvpn.conf
          write-mode: overwrite
          contents: |
            dev tun
            ifconfig 10.8.0.1 10.8.0.2
            secret static.key
      - run: openvpn --config openvpn.conf
        
